version: '3.9'

services:
  frontend:
    image: frontend
    volumes:
       - ./api:/usr/src/app/frontend
       - /usr/src/app/frontend/node_modules
    ports:
      - "3000:${FRONTEND_PORT}"
    build:
      context: ./frontend
      args:
        - NODE_ENV=${NODE_ENV}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      dockerfile: ./Dockerfile
  backend:
    image: backend
    ports:
      - "3100:${BACKEND_PORT}"
    volumes:
       - ./api:/usr/src/app/backend
       - /usr/src/app/backend/node_modules
    build:
      context: ./backend
      args:
        - NODE_ENV=${NODE_ENV}
      dockerfile: ./Dockerfile