name: Docker Image CI

env:
  NEXT_PUBLIC_API_BASE_URL: '{{secrets.NEXT_PUBLIC_API_BASE_URL}}'
  NODE_ENV: '{{secrets.NODE_ENV}}'
  FRONTEND_PORT: '{{secrets.FRONTEND_PORT}}'
  BACKEND_PORT: '{{secrets.BACKEND_PORT}}'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy Multiple Docker Images to Heroku Apps
      # You may pin to the exact commit or the version.
      # uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@a4590bf326a12190449bdd4c07657e048b1ca9d7
      uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
      env:
        FRONTEND_PORT: '{{secrets.FRONTEND_PORT}}'
        BACKEND_PORT: '{{secrets.BACKEND_PORT}}'
      with:
        # Email linked to your Heroku account
        email: ${{ secrets.EMAIL }}
        # Your Heroku API Key
        api_key: ${{ secrets.API_KEY }}
        # docker-compose File Path
        docker_compose_file: 'docker-compose.yml'
        # List of Docker Images generated from docker-compose and Heroku app names with type
        heroku_apps: '[{"imagename":"frontend","appname":"route-history-ui","apptype":"web"},{"imagename":"backend","appname":"route-history-api","apptype":"web"}]'
